### ISSUE TITLE
Variables named "self" in core.js should be renamed to "me"

### ISSUE THREAD

**Issue by bigsur0** [metajack/strophejs#1]
Since "self" is a reserved word in Javascript, the "self" variables created in the Strophe._dataRecv and Strophe.isMatch functions should be renamed to "me". This was silently breaking in Internet Explorer 6,7,8 when a response had more than one element and the Strophe.forEachChild method was invoked in Strophe._dataRecv. I guess it was loosing its scope somehow...Thanks IE!

**Comment by metajack** [comment]
This is fixed in the latest copy of master. Thanks for finding this obscure issue!
