### ISSUE TITLE
login with anonymous users getting not-authorised message

### ISSUE THREAD

**Issue by pokal4u** [metajack/strophejs#105]
Hi,

login with registered users working fine, using anonymous user getting not-authorised error.(first time connected after refresh got this error)

my code:
var connection=null;
connection = new Strophe.Connection(BOSH_SERVICE);

anonymous user-----------> connection.connect('srinu@domain.com/srinu', null, onConnect);------getting not-authorised message
register user----------> connection.connect("admin@domain.com/admin",'password', onConnect);------it's working

we are using strophe with bosh+ejabbered+openfire

Please help me
Pokal4u

**Comment by metajack** [comment]
You need to use "domain.com" or "domain.com/srinu" to log in as anonymous. Specifying a user will trigger regular authentication.

**Comment by pokal4u** [comment]
![code](https://f.cloud.github.com/assets/498771/346911/358fef36-9e79-11e2-82dc-2808f7bd7f42.jpg)
Hi,
Thanks for reply
I tried that way also like
connection.connect("domain.com/pokal4u",null, onConnect);
var message = $msg({to:'domain.com/srinu', from:connection.jid, type: 'chat'}).c('body').t(mes);
connection.send(message.tree());
now successfully connected but not get messages from pokal4u to srinu and srinu to pokal4u

and url open in another tab previous tab disconnected.

and plesae find attached file for my code

it's important for me
Please help me

Pokal4u

**Comment by metajack** [comment]
After you finish anonymous auth your jid will be in connection.jid. it will not be the same one you supplied, since the server assigns a random one.

I think you might gain a lot of understanding from a cursory read of the XMPP spec.

**Comment by pokal4u** [comment]
HI,
Thanks for reply.
Please tell me how can i connect?
Please give me a best example.
Thanks

Pokal4u
