### ISSUE TITLE
Function.prototype.bind is not compatible with the ECMAScript 5.

### ISSUE THREAD

**Issue by tim-evans** [metajack/strophejs#14]
Hey Jack-

The Function.prototype.bind right now in Strophe isn't compatible with browsers that use bind() natively. To ensure compatibility, it'd be nice to see Strophe's bind() take all arguments after the thisArg argument to be curried onto the function.

Thanks!

**Comment by metajack** [comment]
Thanks for noticing this. I must have misread the spec ages ago. This also makes prependArg() useless, so I've changed the code to use bind() and removed prependArg().

The fix is now committed to master.

**Comment by tim-evans** [comment]
That's quick! Thanks for the patch!
