### ISSUE TITLE
I cannot find strophe.js in the download

### ISSUE THREAD

**Issue by mliumike** [metajack/strophejs#17]
I downloaded the 1.0 version and extracted it.  I do not see strophe.js in the expanded directory.

Am I doing something wrong?  

I see the makefile, readme and the other directories like examples etc. but no strophe.js.

Mike

**Comment by metajack** [comment]
The download is currently just a repository snapshot, which does not contain strophe.js. Strophe.js is built from the makefile by concatenating the other files.

**Comment by mliumike** [comment]
I am running RHel 5 64bits.  And I am logged in as root.  I tried running Makefile but it gives me a errors like SRC_DIR is not a command:

[root@localhost strophejs]# ./Makefile
./Makefile: line 3: SRC_DIR: command not found
./Makefile: line 4: DOC_DIR: command not found
./Makefile: line 5: PLUGIN_DIR: command not found
./Makefile: line 6: NDPROJ_DIR: command not found
./Makefile: line 8: SRC_DIR: command not found
./Makefile: line 8: SRC_DIR: command not found
./Makefile: line 8: SRC_DIR: command not found
./Makefile: line 8: BASE_FILES: command not found

Is there any way to get a prebuilt javascript library or does the concatenation have to happen after installation.

**Comment by metajack** [comment]
Makefile isn't meant to be executed. If you simply type 'make' it will build. RedHat should already come with 'make'.

I will work on getting a pre-built one available on GitHub. You can find a slightly older build on http://code.stanziq.com/strophe

**Comment by mliumike** [comment]
Thanks .... I got it working.

**Comment by meinharrd** [comment]
http://code.stanziq.com/strophe now forwards here.. ;) so i put a 1.0.1 build including docs and strophe.js up on http://strophe.benn.org/ - happy downloading :)
