### ISSUE TITLE
BOSH module not started - when using echobot.html

### ISSUE THREAD

**Issue by mliumike** [metajack/strophejs#18]
When using stophe.js version 1.0 echobot.html I get the xml message 'BOSH module not started'.

I have jwchat and also pidgin working.   

In all cases BOSH_SERVICE (echobot.js) is pointing to http://job.myserver.com/http-bind/ 

Direct URL access of http://job.myserver.com/http-bind/ shows: "ejabberd mod_http_bind
An implementation of XMPP over BOSH (XEP-0206)" message.

Is there something I am doing wrong or perhaps you can point me to the right direction.

**Comment by merkabah** [comment]
Add mod_http_bind to your ejabberd config file

**Comment by metajack** [comment]
If that doesn't work, please reopen the bug and let us know what URL your app is running at.

**Comment by mliumike** [comment]
I will see what I can do .. this is a test server and not exposed to the public.

mod_http_bind ... is configured in the ejabberd config file ... I have checked it ... is there a way to see somewhere (like a process ps -ef) that it is running.

**Comment by metajack** [comment]
I don't need hte URL in order to access it. I only ask so that I can check that it is not a cross domain request.

**Comment by mliumike** [comment]
Recall I am having problem with echobot.html working thought the .js points to http://job.myserver.com/http-bind/

It would seem the error is invoked in erlang at:

check_bind_module(XmppDomain) ->
    case gen_mod:is_loaded(XmppDomain, mod_http_bind) of
    true -> ok;
    false -> ?ERROR_MSG("You are trying to use HTTP Bind (BOSH), but the module mod_http_bind is not started.~n"
                "Check your 'modules' section in your ejabberd configuration file.",[])

THIS message "... mod_httpd_bind is not started ... " is recorded in the ejabberd.log and 
also shown by echobot.html.

Going further I noticed in the logs that the connection is accepted under the domain IP 10.0.3.100.   And of course, 10.0.3.100 is the IP for domain name job.myserver.com and that is how ejabberd.cfg is configured and in the webadmin it does show up right, plus, pidgin works, and also jwchat.

IN ERLANG, I was directly able to run the command gen_mod:is_loaded to verify that mod_httpd_bind is loaded for domain job.myserver.com.

HOWEVER, IN ERLANG, using the domain 10.0.3.100 (the domain name's ip), that mod_httpd_bind is not loaded (returns false). 

I SUSPECT THAT AFTER CONNECTION IS ACCEPTED, the domain is checked using the domain IP of 10;0.3.100

PART OF THE LOG WHICH PRECEDES THE MESSAGE mod_http_bind not started and this shows IP of the domain is being used to connect.

=INFO REPORT==== 2011-02-08 11:14:38 ===
I(<0.366.0>:ejabberd_listener:281) : (#Port<0.463>) Accepted connection {{10,0,3,100},40903} -> {{10,0,3,100},5280}

Can you provide suggestions as to how to make connections using domain name as opposed to IP?

Is there something I am doing wrong in my config somewhere?

What do you see when you use echobot.html in the log files?

I deeply realize this is a long post.  I hope you can look at it.

**Comment by esneko** [comment]
You are trying to use BOSH (HTTP Bind) in host XXX, but the module mod_http_bind is not started in that host. Configure your BOSH client to connect to the correct host, or add your desired host to the configuration, or check your 'modules' section in your ejabberd configuration file.

```
{modules,
    [
        {mod_http_bind, []}
    ]
}.
```

**Comment by mliumike** [comment]
Thanks,

**Comment by jimymodi** [comment]
Hi,

I am having the same issue as mliumike stated in 8 February 2011 comment 

@esneko please can you tell me what to do exactly??

@mliumike how did you solved your problem???

**Comment by mliumike** [comment]
I hope you solved your problem.

I was on vacation and just checking my email.

It took me a while to figure it out and I don't remember what exactly I did
and since it was not a high priority project I have not finished it.

But what a number of people were saying that it is a domain mix up problem
is correct.

For some reason, I believe in some places the config was done using
localhost and (if you look at one of my posts), a mix up happens where it
tries to connect to
the server which is not started on the correct host.

Definitely a domain configuration issue.

Mike

**Comment by jimymodi** [comment]
I am still getting the same problem. Dont know whats wrong. As I am only trying to run my friends project on my PC, so was less bothered about it.
