### ISSUE TITLE
HTML escaping fails in Strophe.serialize

### ISSUE THREAD

**Issue by ghost** [metajack/strophejs#19]
Very contrived example:
    var aMsg = $msg({to:'test@example.com', type:'chat', text:'<b>hello</b>'})
    con.send(aMsg);

Which results in a message that fails to send, containing:
    <message to='test@example.com' type='chat' text='&lt;b>hello</b>' xmlns='jabber:client'/>

Offending code, within the function Strophe.serialize:
    result = "<" + nodeName;
        for (i = 0; i < elem.attributes.length; i++) {
               if(elem.attributes[i].nodeName != "_realname") {
                 result += " " + elem.attributes[i].nodeName.toLowerCase() +
                "='" + elem.attributes[i].value
                    .replace("&", "&amp;")
                       .replace("'", "&apos;")
                       .replace("<", "&lt;") + "'";
               }
        }

Proposed fix:
Change Strophe.xmlescape to handle apostrophe and quotes as well, and use it in serialize.
    xmlescape: function(text)
    {
        text = text.replace(/&/g, "&amp;");
        text = text.replace(/</g,  "&lt;");
        text = text.replace(/>/g,  "&gt;");
        text = text.replace(/"/g,  "&quot;");
        text = text.replace(/'/g,  "&#39;");
        return text;
    },

Then within Strophe.serialize we'll have:
            result += " " + elem.attributes[i].nodeName.toLowerCase() +
                "='" + Strophe.xmlescape(elem.attributes[i].value) + "'";

EDIT: This is Strophe v1.0, on both Chrome 8 and Firefox 3.6.
EDIT2: Found the issue. See above.

**Comment by theozaurus** [comment]
I've made a pull request for this issue in a similar fashion to mihaid solution, but it also preserves CDATA sections correctly. Tests are provided as well.

https://github.com/metajack/strophejs/pull/53

**Comment by astro** [comment]
Pull request #53 was closed.
