### ISSUE TITLE
Disconnect twice

### ISSUE THREAD

**Issue by benlangfeld** [metajack/strophejs#2]
Unfortunately I couldn't get the real issue tracker to let me login, so I have to post this here. Apologies.

I'm seeing Strophe.js post two presence unavailable stanzas to prosody's mod_bosh on disconnect (using the basic strophe.js example). This is confirmed by the prosody log as here: http://conference.prosody.im:5280/pastebin/be70c7d8-623b-4ec6-9988-b30b7cc8cfa4

In Firefox and Chrome (both on OS X, most recent stable versions), the strophe raw output looks like this: http://gist.github.com/509544, but on Safari only one presence unavailable is printed but two are still sent.

**Comment by benlangfeld** [comment]
This is fixed here: http://github.com/metajack/strophejs/pull/7

**Comment by metajack** [comment]
This has been merged with master. Thanks for finding this and fixing it!
