### ISSUE TITLE
how to use strophe to dynamically create rooms for users and friends

### ISSUE THREAD

**Issue by foo123** [metajack/strophejs#80]
hi,
i have an application which has users which have friends etc. the app will have chat service for the users.the problem is i can get a list of the users friends and i want to be able to create a chat room on the fly for this group of people and transmit it to all other friends of the user to be able to join
is this possible with strophe.js

thanx

**Comment by astro** [comment]
http://xmpp.org/extensions/xep-0045.html#enter-muc
http://xmpp.org/extensions/xep-0045.html#invite

**Comment by foo123** [comment]
thanx for your fast reply, im already aware of the muc plugin, the main problem is how to coordinate the users to join the same room since each is logged at different times and pages
the scenario is the following:
a user logs in> i am provided with the login information and the list of other users who are friends> i log the user to the chat server (openfire)> another user logs in who is a friend of the previous user> how create a room on the fly and propagate this information to the second user (and also all other friends) so that when they login they see the room and presence
initially there is no room
how to get presence with no room and then create the room?

thanx again

**Comment by astro** [comment]
On most conference services the room will be auto-created when the first participant joins.

**Comment by foo123** [comment]
i'm not sure i understand, can you be more specific (i dont want detailed code, just the general strategy).
The problem is how to keep track and synchronize users with the chat service. The problem is how each group of users (ie friends) can dynamically synchronize with the same room automatically (we can assume the room will be created when the first user of the group logs in, then others will follow) ie a user logs in and he can immediately send /receive messages from his friends only. i must say that part of the chat app is already functioning (all users auto-join a common/global room) and each user can change its status/prsence as they wish (online/offline/away) using strophe.js and muc plugin.

thanx
