### ISSUE TITLE
Implement In-Band Registration

### ISSUE THREAD

**Issue by nadimkobeissi** [metajack/strophejs#90]
Please implement in-band registration, allowing Strophe.js to register new accounts. I believe this is an absolutely crucial functionality. http://xmpp.org/extensions/xep-0077.html

PS: Reading your book! Thanks!

**Comment by dodo** [comment]
done: https://github.com/metajack/strophejs-plugins/tree/master/register

**Comment by nadimkobeissi** [comment]
Awesome, thank you!
